spring.application.name=fintech-api

spring.datasource.url=jdbc:postgresql://localhost:5432/fintech
spring.datasource.username=postgres
spring.datasource.password=nibin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true