spring.application.name=fintech-api

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/fintech
spring.datasource.username=postgres
spring.datasource.password=nibin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# jwt (sample one created myself)
jwt.secret=Kj8sP2v9Lx7mQ4rT6yU1zW3aB5cD8eF0GhIjKlMnOpQrStUv
jwt.expiration=3600000